---
platform: linux
image_resource:
    type: docker-image
    source: 
        repository: laidbackware/ansible-aio
        tag: latest
    # source: 
    #     repository: hashicorp/terraform
    #     tag: 0.11.14
inputs:
- name: platform-repo
params:
    OUTPUT_FILE_NAME:
        # - Required
    DOWNLOAD_LINK: 
    # - Required
    VERSION_CHECK_COMMAND: 
        # - Required
outputs:
- name: downloaded-product

run:
    path: platform-repo/tasks/download-with-wget/task.sh