---
platform: linux
image_resource:
    type: docker-image
    source: 
        repository: laidbackware/ansible-aio
        tag: latest
inputs:
- name: platform-repo
- name: jq-cli
outputs:
- name: downloaded-product

run:
    path: platform-repo/tasks/download-terraform/task.sh